databases:
  conf1:
    db: "tinkergraph"
    enabled: false
  conf2:
    db: "overflowdb"
    enabled: true
    storage: "/tmp/plume/cpg.bin"
    set_overflow: false
    set_heap_percentage_threshold: 80
    set_serialization_stats_enabled: false
  conf3:
    db: "janus-berkeleyje-lucene"
    enabled: false
    containers:
      - "janus-berkeleyje-lucene"
    remote_config: "src/main/resources/conf/remote-graph.properties"
  conf4:
    db: "janus-scylla-es"
    enabled: false
    containers:
      - "janus-plume-benchmark"
      - "scylla-plume-benchmark"
      - "elastic-plume-benchmark"
    remote_config: "src/main/resources/conf/remote-graph.properties"
  conf5:
    db: "tigergraph"
    enabled: false
    containers:
      - "tigergraph-plume-benchmark"
    username: "tigergraph"
    password: "tigergraph"
    hostname: "127.0.0.1"
    restPpPort: 9000
    gsqlPort: 14240
    secure: false
#    auth_key: "secret"
  conf6:
    db: "neptune"
    enabled: false
    hostnames:
      - "127.0.0.1"
    port: 8182
    key_cert_chain_file: "src/test/resources/conf/SFSRootCAG2.pem"
  conf7:
    db: "neo4j"
    enabled: false
    containers:
      - "neo4j-plume-benchmark"
    hostname: "127.0.0.1"
    port: 7687
    username: "neo4j"
    password: "neo4j123"
    database: "neo4j"