iterations: 1

programs:
  conf1:
    enabled: true
    name: "FasterXML/jackson-databind"
    init-jar: "492fb802380f38ea3a5a31446bc53cb895cca029"
    update-jar: "4adcbff5373bf0bde7a12760a83e340762b03aa0"
  conf2:
    enabled: true
    name: "apache/tinkerpop/gremlin-driver"
    init-jar: "8729fd4ce1711b29bc0b90670e87df33e91f4f09"
    update-jar: "ee61241999eeb12b9d3fc8d64a3f9a06f6ba47f0"

databases:
  conf1:
    db: "TinkerGraph"
    enabled: true
  conf2:
    db: "OverflowDB"
    enabled: true
    storage: "/tmp/plume/cpg.bin"
    set_overflow: false
    set_heap_percentage_threshold: 80
    set_serialization_stats_enabled: false
  conf3:
    db: "JanusGraph_BerkeleyJE_Lucene"
    enabled: false
    containers:
      - "janus-berkeleyje-lucene"
    remote_config: "src/main/resources/conf/remote-graph.properties"
  conf4:
    db: "JanusGraph_Scylla_ElasticSearch"
    enabled: true
    containers:
      - "janus-plume-benchmark"
      - "scylla-plume-benchmark"
      - "elastic-plume-benchmark"
    remote_config: "src/main/resources/conf/remote-graph.properties"
  conf5:
    db: "TigerGraph"
    enabled: true
    containers:
      - "tigergraph-plume-benchmark"
    username: "tigergraph"
    password: "tigergraph"
    hostname: "127.0.0.1"
    restPpPort: 9000
    gsqlPort: 14240
    secure: false
#    auth_key: "secret"
  conf6:
    db: "Neptune"
    enabled: false
    hostnames:
      - "127.0.0.1"
    port: 8182
    key_cert_chain_file: "src/test/resources/conf/SFSRootCAG2.pem"
  conf7:
    db: "Neo4j"
    enabled: true
    containers:
      - "neo4j-plume-benchmark"
    hostname: "127.0.0.1"
    port: 7687
    username: "neo4j"
    password: "neo4j123"
    database: "neo4j"
  conf8:
    db: "TigerGraph_Cloud"
    enabled: false
    username: "tigergraph"
    password: "PlumeBench"
    hostname: "plume-benchmarking-1.i.tgcloud.io"
    restPpPort: 9000
    gsqlPort: 14240
    secure: true
    # auth_key: ""
