version: '3'
services:
  neo4j:
    image: bitnami/neo4j:4-debian-10
    container_name: neo4j-plume-benchmark
    environment:
      NEO4J_PASSWORD: "neo4j123"
    ports:
      - "7687:7687"
      - "7474:7474"
    healthcheck:
      test: perl -MIO::Socket::INET -e 'exit(! defined( IO::Socket::INET->new("localhost:7687")))'
      interval: 5s
      timeout: 10s
      retries: 5
#    volumes:
#      - '../conf/neo4j.conf:/bitnami/neo4j/conf/neo4j.conf'
    stdin_open: true
    tty: true
