TIME_COLUMNS = ['COMPILING_AND_UNPACKING', 'SOOT', 'PROGRAM_STRUCTURE_BUILDING', 'BASE_CPG_BUILDING', 'DATA_FLOW_PASS']

ROOT_DIRECTORY = '../../results/'
RESULT_FILE = ROOT_DIRECTORY + 'result.csv'
MEMORY_FILE = ROOT_DIRECTORY + 'memory_results.csv'
